export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    VERIFY_ACCOUNT: "/verify-account",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
  },
  ADMIN: {
    DASHBOARD: "/admin",
    CONFIG: "/admin/config",
    DEPARTMENTS: "/admin/departments",
    ROOMS: "/admin/rooms",
    USERS: {
      STUDENTS: "/admin/users/students",
      TEACHERS: "/admin/users/teachers",
      COORDINATORS: "/admin/users/coordinators",
    },
    AUDIT_LOGS: "/admin/audit-logs",
  },
  COORDINATOR: {
    DASHBOARD: "/coordinator",
    SCHEDULE: "/coordinator/schedule",
    PROJECTS: "/coordinator/projects",
    JURIES: "/coordinator/juries",
    DEFENSE_SESSIONS: "/coordinator/defense-sessions",
    CONFLICTS: "/coordinator/conflicts",
    GRADES: "/coordinator/grades",
    DOCUMENTS: "/coordinator/documents",
  },
  TEACHER: {
    DASHBOARD: "/teacher",
    SCHEDULE: "/teacher/schedule",
    EVALUATIONS: "/teacher/evaluations",
    UNAVAILABILITY: "/teacher/unavailability",
  },
  STUDENT: {
    DASHBOARD: "/student",
    GROUP: "/student/group",
    DOCUMENTS: "/student/documents",
  },
  SHARED: {
    PROFILE: "/profile",
    NOTIFICATIONS: "/notifications",
  },
  PRINT: {
    EVALUATION_SHEET: "/print/evaluation-sheet",
    ATTENDANCE_LIST: "/print/attendance-list",
    JURY_CONVOCATION: "/print/jury-convocation",
    SCHEDULE: "/print/schedule",
    PROCES_VERBAL: "/print/proces-verbal",
    STUDENT_CONVOCATION: "/print/student-convocation",
  },
} as const;

export const VALID_DASHBOARD_ROUTES = new Set([
  ROUTES.ADMIN.DASHBOARD,
  ROUTES.ADMIN.CONFIG,
  ROUTES.ADMIN.DEPARTMENTS,
  ROUTES.ADMIN.ROOMS,
  ROUTES.ADMIN.USERS.STUDENTS,
  ROUTES.ADMIN.USERS.TEACHERS,
  ROUTES.ADMIN.USERS.COORDINATORS,
  ROUTES.ADMIN.AUDIT_LOGS,
  ROUTES.COORDINATOR.DASHBOARD,
  ROUTES.COORDINATOR.SCHEDULE,
  ROUTES.COORDINATOR.PROJECTS,
  ROUTES.COORDINATOR.JURIES,
  ROUTES.COORDINATOR.DEFENSE_SESSIONS,
  ROUTES.COORDINATOR.CONFLICTS,
  ROUTES.COORDINATOR.GRADES,
  ROUTES.COORDINATOR.DOCUMENTS,
  ROUTES.TEACHER.DASHBOARD,
  ROUTES.TEACHER.SCHEDULE,
  ROUTES.TEACHER.EVALUATIONS,
  ROUTES.TEACHER.UNAVAILABILITY,
  ROUTES.STUDENT.DASHBOARD,
  ROUTES.STUDENT.GROUP,
  ROUTES.STUDENT.DOCUMENTS,
  ROUTES.SHARED.PROFILE,
  ROUTES.SHARED.NOTIFICATIONS,
]);

export const BREADCRUMB_LABELS: Record<string, string> = {
  [ROUTES.ADMIN.DASHBOARD]: "Admin",
  [ROUTES.ADMIN.CONFIG]: "Configuration",
  [ROUTES.ADMIN.DEPARTMENTS]: "Départements",
  [ROUTES.ADMIN.ROOMS]: "Salles",
  "/admin/users": "Utilisateurs",
  [ROUTES.ADMIN.USERS.STUDENTS]: "Étudiants",
  [ROUTES.ADMIN.USERS.TEACHERS]: "Enseignants",
  [ROUTES.ADMIN.USERS.COORDINATORS]: "Coordinateurs",
  [ROUTES.ADMIN.AUDIT_LOGS]: "Audit Log",

  [ROUTES.COORDINATOR.DASHBOARD]: "Coordinateur",
  [ROUTES.COORDINATOR.SCHEDULE]: "Planification",
  [ROUTES.COORDINATOR.PROJECTS]: "Projets & Groupes",
  [ROUTES.COORDINATOR.JURIES]: "Jurys",
  [ROUTES.COORDINATOR.DEFENSE_SESSIONS]: "Sessions de soutenance",
  [ROUTES.COORDINATOR.CONFLICTS]: "Conflits",
  [ROUTES.COORDINATOR.GRADES]: "Notes",
  [ROUTES.COORDINATOR.DOCUMENTS]: "Documents",

  [ROUTES.TEACHER.DASHBOARD]: "Enseignant",
  [ROUTES.TEACHER.SCHEDULE]: "Planification",
  [ROUTES.TEACHER.EVALUATIONS]: "Évaluations",
  [ROUTES.TEACHER.UNAVAILABILITY]: "Indisponibilités",

  [ROUTES.STUDENT.DASHBOARD]: "Étudiant",
  [ROUTES.STUDENT.GROUP]: "Groupe",
  [ROUTES.STUDENT.DOCUMENTS]: "Documents",

  [ROUTES.SHARED.PROFILE]: "Profil",
  [ROUTES.SHARED.NOTIFICATIONS]: "Notifications",
};
